language: bash
services: docker

env:
  - VERSION=2.6-rc VARIANT=stretch
  - VERSION=2.6-rc VARIANT=stretch/slim
  - VERSION=2.6-rc VARIANT=alpine3.7
  - VERSION=2.5 VARIANT=stretch
  - VERSION=2.5 VARIANT=stretch/slim
  - VERSION=2.5 VARIANT=alpine3.7
  - VERSION=2.4 VARIANT=stretch
  - VERSION=2.4 VARIANT=stretch/slim
  - VERSION=2.4 VARIANT=jessie
  - VERSION=2.4 VARIANT=jessie/slim
  - VERSION=2.4 VARIANT=alpine3.7
  - VERSION=2.4 VARIANT=alpine3.6
  - VERSION=2.4 VARIANT=alpine3.4
  - VERSION=2.3 VARIANT=stretch
  - VERSION=2.3 VARIANT=stretch/slim
  - VERSION=2.3 VARIANT=jessie
  - VERSION=2.3 VARIANT=jessie/slim
  - VERSION=2.3 VARIANT=alpine3.4
  - VERSION=2.2 VARIANT=jessie
  - VERSION=2.2 VARIANT=jessie/slim
  - VERSION=2.2 VARIANT=alpine3.4

install:
  - git clone --depth 1 https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - slash='/'; image="ruby:${VERSION}-${VARIANT//$slash/-}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      travis_retry docker build -t "$image" .
      ~/official-images/test/run.sh "$image"
      if [ -d onbuild ]; then
        onbuildFrom="$(awk 'toupper($1) == "FROM" { print $2; exit }' onbuild/Dockerfile)"
        docker tag "$image" "$onbuildFrom"
        docker build -t "$image-onbuild" onbuild
        ~/official-images/test/run.sh "$image-onbuild"
      fi
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
