language: bash
services: docker

env:
  - VERSION=2.6 VARIANT=stretch
  - VERSION=2.6 VARIANT=stretch/slim
  - VERSION=2.6 VARIANT=alpine3.9
  - VERSION=2.6 VARIANT=alpine3.8
  - VERSION=2.5 VARIANT=stretch
  - VERSION=2.5 VARIANT=stretch/slim
  - VERSION=2.5 VARIANT=alpine3.9
  - VERSION=2.5 VARIANT=alpine3.8
  - VERSION=2.4 VARIANT=stretch
  - VERSION=2.4 VARIANT=stretch/slim
  - VERSION=2.4 VARIANT=jessie
  - VERSION=2.4 VARIANT=jessie/slim
  - VERSION=2.4 VARIANT=alpine3.9
  - VERSION=2.4 VARIANT=alpine3.8

install:
  - git clone --depth 1 https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - slash='/'; image="ruby:${VERSION}-${VARIANT//$slash/-}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      travis_retry docker build -t "$image" .
      ~/official-images/test/run.sh "$image"
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
